# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Electron Application (Windows)

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

 schedule:
    # CRON this build
    - cron: '40 10 1 * *'

 workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && npm run build
    - name: Build for Windows x64
      run: npm run package-win-x64
      env:
        testing: no
    - name: Zip Build
      run: ls && tar -cvzf build.tar .\out\
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          # Artifact name
          name: build_win-latest.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: build.tar
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 1
